# Generated by Django 2.1.1 on 2018-09-15 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_ratings_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogposts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.RenameModel(
            old_name='ratings',
            new_name='rating',
        ),
        migrations.RenameModel(
            old_name='reviews',
            new_name='review',
        ),
    ]
